spring.application.name=pingpong
server.port=${PORT:8080}

# 환경 변수를 통해 DB에 접속 (비밀번호 노출 방지)
spring.datasource.url=jdbc:postgresql://ep-jolly-recipe-ao363b2h-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Diuqmd5zYX4U
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (PostgreSQL용)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true